Repository GigaChatTeam/RTCD, pull requests merged in 2023-12, with the labels that each got.

#7 Updating the startup logic
  Starter.java
Labels: dev

#8 Cleanup DB-operators
  WSCore.java
  dbexecutors/ChannelsExecutor.java
  dbexecutors/DBOperator.java
  dbexecutors/Helper.java
  dbexecutors/PermissionOperator.java
  dbexecutors/SystemExecutor.java
  dbexecutors/TTIntentions.java
Labels: dev

#9 The logic of the Jsoniter extension has been changed
  JsonIteratorExtra.java
  Starter.java
Labels: dev

#10 Fixed issues with syncing expected clients
  Authorizer.java
  Clients.java
  ExpectedClient.java
Labels: dev

#11 Applying changes of bug fixes and optimizations
  .gitignore
  Authorizer.java
  Clients.java
  ExpectedClient.java
  Helper.java
  JsonIteratorExtra.java
  Starter.java
  WSCore.java
  dbexecutors/ChannelsExecutor.java
  dbexecutors/DBOperator.java
  dbexecutors/Helper.java
  dbexecutors/PermissionOperator.java
  dbexecutors/SystemExecutor.java
  dbexecutors/TTIntentions.java
  pom.xml
Labels: dev

#13 Added support for packages related to the user's presence in channels
  Commands.java
  CommandsPatterns.java
  ResponsesPatterns.java
  WSCore.java
  dbexecutors/ChannelsExecutor.java
  exceptions/AlreadyCompleted.java
Labels: dev

#12 The logic of deserialization of the Timestamp type has been changed
  JsonIteratorExtra.java
Labels: hot fix

#14 Adding commands, fixing the serializer, technical changes
  .github/workflows/build.yml
  Clients.java
  Commands.java
  CommandsPatterns.java
  ConnectedClient.java
  Helper.java
  JsonIteratorExtra.java
  ResponsesPatterns.java
  WSCore.java
  dbexecutors/ChannelsExecutor.java
  exceptions/AlreadyCompleted.java
Labels: documentation, dev
